name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # ✅ Grant write access to PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify GitHub CLI Installation
        run: gh --version

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Details
        id: pr_details
        run: |
          echo "Fetching PR details..."
          PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          gh pr diff ${{ github.event.pull_request.number }} > pr_diff.txt
          
          echo "PR Title: $PR_TITLE"
          echo "PR Body: $PR_BODY"
          echo "Extracting diff (first 500 chars for debug):"
          head -c 500 pr_diff.txt
          
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call ChatGPT API
        id: chatgpt
        run: |
          DIFF_CONTENT=$(cat pr_diff.txt | head -c 4000)  # Reduce size for OpenAI API

          # Construct API request
          REQUEST_BODY=$(jq -n --arg title "$PR_TITLE" --arg body "$PR_BODY" --arg diff "$DIFF_CONTENT" '{
            model: "gpt-4",
            messages: [
              { role: "system", content: "You are an expert code reviewer. Provide constructive feedback on the PR title, body, and code diff." },
              { role: "user", content: ("PR Title: " + $title + "\nPR Body: " + $body + "\nCode Diff:\n" + $diff) }
            ]
          }')

          echo "Sending request to OpenAI..."
          echo "Request Body (trimmed):"
          echo "$REQUEST_BODY" | head -c 500

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_BODY" | jq -r '.choices[0].message.content')

          echo "ChatGPT Response: $RESPONSE"

          if [[ -z "$RESPONSE" || "$RESPONSE" == "null" ]]; then
            echo "No valid response from ChatGPT."
            exit 1
          fi

          echo "REVIEW=$RESPONSE" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on PR
        run: |
          echo "Adding ChatGPT review to PR..."
          gh pr comment ${{ github.event.pull_request.number }} --body "$REVIEW"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}





