name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify GitHub CLI Installation
        run: gh --version

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Details
        id: pr_details
        run: |
          echo "PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_DIFF=$(gh pr diff ${{ github.event.pull_request.number }})" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call ChatGPT API
        id: chatgpt
        run: |
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "You are an expert code reviewer. Provide constructive feedback on the PR title, body, and code diff."},
                {"role": "user", "content": "PR Title: $PR_TITLE\nPR Body: $PR_BODY\nCode Diff:\n$PR_DIFF"}
              ]
            }' | jq -r '.choices[0].message.content')
          echo "REVIEW=$RESPONSE" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "$REVIEW"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


