name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ensure compatibility with the action

      - name: Enable Debug Mode
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r /home/runner/work/_actions/sshnaidm/gpt-code-review-action/v2.0/requirements.txt || true

      - name: Run GPT Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Ensure this secret is set in your repository
        uses: sshnaidm/gpt-code-review-action@v2.0
