name: OpenAI Code Review

on:
  pull_request:

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Enable Debug Mode
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Run OpenAI Code Review
        uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}  # Make sure this secret exists!
          github-token: ${{ secrets.GITHUB_TOKEN }}      # Provides permission to post comments
          model: 'gpt-4'
          max-length: 8000
          prompt: 'Review this code for best practices, security, and performance improvements.'
          post-if-error: true

